# Generated by Django 5.2.3 on 2025-08-12 02:04

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Livro')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('cover_image', models.ImageField(upload_to='book_covers/', verbose_name='Imagem da Capa')),
                ('pdf_file', models.FileField(storage=config.storages.PrivateMediaStorage(), upload_to='private_books/', verbose_name='Arquivo PDF')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['-published_at'],
            },
        ),
    ]
