# Generated by Django 5.2.3 on 2025-06-21 15:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text="Usado na URL da página. Ex: 'sobre-nos'. Use apenas letras, números e hifens.", unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteúdo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Página Estática',
                'verbose_name_plural': 'Páginas Estáticas',
            },
        ),
    ]
