# Generated by Django 5.2.3 on 2025-06-22 22:50

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Tipo de Equipamento')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('technical_manual', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='equipment_manuals/', verbose_name='Manual Técnico')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Laboratório')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('inspectors', models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='inspected_labs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('status', models.CharField(choices=[('operacional', 'Operacional'), ('manutencao', 'Em Manutenção'), ('desativado', 'Desativado')], default='operacional', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notas de Manutenção')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='inventory.equipmenttype')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='inventory.laboratorio')),
            ],
        ),
    ]
