# Generated by Django 5.2.3 on 2025-07-09 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Laboratório',
                'verbose_name_plural': 'Tipos de Laboratório',
            },
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('projeto', 'Em Projeto'), ('instalacao', 'Em Instalação'), ('manutencao', 'Em Manutenção')], default='projeto', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='lab_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratorios', to='inventory.laboratoriotype', verbose_name='Tipo de Laboratório'),
        ),
    ]
