# Generated by Django 5.2.3 on 2025-06-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='camera_pos_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Câmera Posição X'),
        ),
        migrations.AddField(
            model_name='part',
            name='camera_pos_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Câmera Posição Y'),
        ),
        migrations.AddField(
            model_name='part',
            name='camera_pos_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Câmera Posição Z'),
        ),
    ]
