# Generated by Django 5.2.3 on 2025-06-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_part_stl_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='part_thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='part_thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
