# Generated by Django 5.2.3 on 2025-06-20 20:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_part_thumbnail_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='part_thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='part_thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
