# Generated by Django 5.2.3 on 2025-06-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_part_thumbnail_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_hall_of_fame',
            field=models.BooleanField(default=False, verbose_name='Destaque (Hall da Fama)'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_hall_of_fame',
            field=models.BooleanField(default=False, verbose_name='Destaque (Hall da Fama)'),
        ),
    ]
